Update conditional_access_policy.md
Add missing value to "included_applications" attribute for setting no included applications. 
If this value isn't set to "None" Terraform fails with the following error:

Error: Could not create conditional access policy
│ 
│   with module.conditional-access.azuread_conditional_access_policy.block_basic_auth_policy,
│   on ../conditional-access/main.tf line 30, in resource "azuread_conditional_access_policy" "block_basic_auth_policy":
│   30: resource "azuread_conditional_access_policy" "block_basic_auth_policy" {
│ 
│ ConditionalAccessPoliciesClient.BaseClient.Post(): unexpected status 500 with OData error: Internal Server Error: There was an internal server error while processing the request. Error ID: c9b4f7ac-cbe5-45fe-8d4c-16961e3b872f